In [1]:
#Import modules

import pandas as pd
import numpy as np

In [ ]:
pd.set_option('display.max_rows', 6000)
pd.set_option('display.max_columns', 500)

In [24]:
#Read columns
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [26]:
#Column Activity
da = df.groupby('Activity')
da.first()

,Case Number,Date,Year,Type,Country,Area,Location,Name,Sex,Age,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
Activity,,,,,,,,,,,,,,,,,,,,,
,1900.07.00,Late Jul-1900,1900,Provoked,USA,Connecticut,"Bridgeport, Fairfield County","skiff with Dr. William T. Healey, Dr. Henry Ca...",NaN,NaN,...,NaN,"Times, 8/1/1900",1900.07.00-Bridgeport.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1900.07.00,1900.07.00,672,NaN,NaN
,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,"canoe, occupants: Chris Newman & Stewart Newman",M,32 & 30,...,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.01.04,1993.01.04,3708,NaN,NaN
a canoe was pursuing a schooner that had forcibily abducted 5 young girls,1892.03.25.R,Reported 25-Mar-1893,1892,Unprovoked,PACIFIC OCEAN,NaN,NaN,NaN,M,NaN,...,NaN,"West Australian, 3/25/1892",1892.03.25.R-Canoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1892.03.25.R,1892.03.25.R,552,NaN,NaN
"""Boat accident""",1895.05.03,03-May-1895,1895,Unprovoked,NEW ZEALAND,South Island,Preservation Inlet,James Cromarty,M,NaN,...,NaN,"Otago Witness, 5/16/1895",1895.05.03-Cromarty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1895.05.03,1895.05.03,596,NaN,NaN
"""Climbing up to ship after repairing the stern in water""",1958.09.13,13-Sep-58,1958,Unprovoked,ANDAMAN / NICOBAR ISLANDAS,NaN,NaN,Sailor of tuna vessel Daisan-Tenyo-Maru,M,32,...,Blue shark,M. Hosina,1958.09.13-sailor.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1958.09.13,1958.09.13,2079,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ship torpedoed 400 miles off the African coas. Man was clinging to hatch cover,1943.05.01.R,Reported 01-May-1943,1943,Sea Disaster,INDIAN OCEAN,NaN,NaN,Clarence Master,M,NaN,...,Blue shark,"St. Petersburg Times, 5/1/1943",1943.05.01.R-Clarence-Master.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1943.05.01.R,1943.05.01.R,1543,NaN,NaN
small boat,1893.10.16,16-Oct-1893,1893,Invalid,CROATIA,Primorje-Gorski Kotar County,"Off Volusca, Opatija",4 passengers frightened by shark,NaN,NaN,...,NaN,C. Moore,1893.10.16-Opatija.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1893.10.16,1893.10.16,572,NaN,NaN
wreck of the State Oil Company ship Permina,1966.01.25,25-Jan-66,1966,Sea Disaster,INDONESIA,North Sumatra,Near Belawan,NaN,NaN,NaN,...,NaN,Sydney Daily Telegraph,1966.01.25-Permina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1966.01.25,1966.01.25,2631,NaN,NaN
yachting accident,1884.12.13,13-Dec-1884,1884,Sea Disaster,AUSTRALIA,South Australia,Port Phillip,Willaim Browne,M,NaN,...,14' shark,"The Argus, 12/29/1884",1884.12.13-Browne.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1884.12.13,1884.12.13,465,NaN,NaN
yachtsman in a zodiac,ND.0096,No date,0,Unprovoked,REUNION,Grand'Anse,Petite-�le,NaN,M,NaN,...,NaN,G. Van Grevelynghe,ND-0096-Zodiac-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0096,ND.0096,85,NaN,NaN

In [33]:
#Count a column
df.groupby(['Sex ']).count()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Age,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
Sex,,,,,,,,,,,,,,,,,,,,,
.,1,1,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,1,1,0,0
F,585,585,585,585,582,567,560,536,580,426,...,323,582,585,585,584,585,585,585,0,0
M,4835,4835,4835,4835,4798,4507,4430,4509,4778,2841,...,2468,4824,4835,4834,4833,4835,4835,4835,1,2
M,2,2,2,2,2,2,2,2,2,1,...,1,2,2,2,2,2,2,2,0,0
N,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,0,0
lli,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0

In [40]:
#Look for values in a column

db = df["Unnamed: 22"].value_counts()
db

stopped here    1
Name: Unnamed: 22, dtype: int64

In [43]:
#Look for not null
dc = df[(df["Unnamed: 22"].isnull() == False)]
dc

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,...,NaN,globalsurfnews.com,2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.18,2006.06.18,4746,stopped here,NaN

In [49]:
de = df[(df["Species "].isnull() == False)]
de

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27,NaN,NaN
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10,NaN,NaN
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9,NaN,NaN
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8,NaN,NaN
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7,NaN,NaN

In [51]:
dg = df[df['Activity'] == 'Surfing']
dg

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,1922.01.04,04-Jan-22,1922,Unprovoked,AUSTRALIA,New South Wales,"Stockton Beach, Newcastle",Surfing,John Manning Rowe,M,...,NaN,"The Argus, 1/9/1922; V.M. Coppleson (1933), N15",1922.01.04-JManningRowe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1922.01.04,1922.01.04,989,NaN,NaN
5048,1918.03.22,22-Mar-18,1918,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Surfing,Arthur Cook,M,...,12' shark,"The Advertiser, 3/25/1918",1918.03.22-Cook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1918.03.22,1918.03.22,945,NaN,NaN
5808,1828.00.00,1828,1828,Unprovoked,USA,Hawaii,"Uo, Lahaina, Maui",Surfing,Male,M,...,NaN,"J. Borg, p.68; L. Taylor (1993), pp.94-95",1828.00.00-male.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1828.00.00,1828.00.00,185,NaN,NaN
5837,1779.00.00,1779,1779,Unprovoked,USA,Hawaii,"Maliu, Hawai'i",Surfing,Nu'u-anu-pa'a hu,M,...,NaN,"G.H. Balazs; J. Borg, p.68; L. Taylor (1993), ...",1779.00.00-Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1779.00.00,1779.00.00,156,NaN,NaN
5891,ND-0122,Beforer 1994,0,Unprovoked,USA,Florida,"Lost Tree Village, Palm Beach County",Surfing,C.M,M,...,NaN,M. Vorenberg,ND-0122-CM.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0122,ND-0122,102,NaN,NaN

In [53]:
dh = df.Country.value_counts()
dh

USA                 2116
AUSTRALIA           1279
SOUTH AFRICA         565
PAPUA NEW GUINEA     133
NEW ZEALAND          125
                    ...
BANGLADESH             1
RED SEA?               1
ICELAND                1
MEXICO                 1
RED SEA                1
Name: Country, Length: 203, dtype: int64

In [56]:
dj = dict(df['Activity'].value_counts())
dj

{'Surfing': 904,
 'Swimming': 819,
 'Fishing': 414,
 'Spearfishing': 321,
 'Bathing': 153,
 'Wading': 144,
 'Diving': 123,
 'Standing': 97,
 'Snorkeling': 77,
 'Scuba diving': 74,
 'Body boarding': 54,
 'Body surfing': 48,
 'Swimming ': 47,
 'Pearl diving': 32,
 'Treading water': 32,
 'Kayaking': 28,
 'Boogie boarding': 28,
 'Free diving': 26,
 'Fell overboard': 21,
 'Windsurfing': 18,
 'Boogie Boarding': 16,
 'Shark fishing': 15,
 'Walking': 15,
 'Rowing': 12,
 'Surf-skiing': 12,
 'Fishing ': 12,
 'Canoeing': 12,
 'Surf skiing': 12,
 'Floating': 12,
 'Surf fishing': 11,
 'Fishing for sharks': 11,
 'Kayak Fishing': 10,
 'Sponge diving': 10,
 'Freediving': 10,
 'Sitting on surfboard': 9,
 'Diving for trochus': 9,
 'Sailing': 9,
 'Fell into the water': 8,
 'Sea disaster': 8,
 'Spearfishing ': 7,
 'Diving for abalone': 7,
 'Paddle boarding': 7,
 'Playing': 7,
 'Boating': 7,
 'Free diving for abalone': 7,
 'Floating on his back': 7,
 'Surfing (sitting on his board)': 7,
 'Skindiving': 7,
 'Surf skiing ': 6,
 'Spearfishing on Scuba': 6,
 'Fishing for mackerel': 6,
 'Sea Disaster': 6,
 'Murder': 6,
 'Kite Surfing': 6,
 'Freedom swimming': 5,
 'Boat': 5,
 'Shipwreck': 5,
 'Hard hat diving': 5,
 'Paddleskiing': 5,
 'Fishing on a boat': 5,
 'Dangling feet in the water': 5,
 'Scuba diving (but on surface)': 4,
 'Clamming': 4,
 'Fishing boat': 4,
 'Scuba diving (submerged)': 4,
 'Jumped into the water': 4,
 'Jumping': 4,
 'Diving for coins': 4,
 'Wade Fishing': 4,
 'Skin diving': 4,
 'Body-boarding': 4,
 'Stand-Up Paddleboarding': 4,
 'Spearfishing / free diving': 4,
 'Freedom Swimming': 4,
 'Seine netting': 4,
 'Splashing': 4,
 'Lifesaving drill': 4,
 'Paddling on surfboard': 4,
 'Tagging sharks': 3,
 'Fishing for bluefish': 3,
 'Shark watching': 3,
 'Feeding fish': 3,
 'Spearing fish': 3,
 'Walking out of the water after surfing': 3,
 'Surfing ': 3,
 'Scuba diving for abalone': 3,
 'boat capsized': 3,
 'Jumped overboard': 3,
 'Spearfishing (free diving)': 3,
 'Sculling': 3,
 'Wade fishing': 3,
 'Surfing, paddling seawards': 3,
 'Escaping from Alacatraz': 3,
 'Competing in the Woodvale Atlantic Rowing Race': 3,
 'Crayfishing': 3,
 'Hookah diving for abalone': 3,
 'Free diving & spearfishing': 3,
 'Fishing for snapper': 3,
 'SCUBA diving': 3,
 'Playing in the surf': 3,
 'Unknown': 3,
 'Floating on a raft': 3,
 'Wade-fishing': 3,
 'Crabbing': 3,
 'Shell diving': 3,
 'Spearfishing / Scuba diving (at surface)': 3,
 'Kite surfing': 3,
 'Boat swamped': 3,
 'Sitting on gunwale of boat': 3,
 '.': 3,
 'Kayaking / Fishing': 3,
 'Body Boarding': 3,
 'Fishing for kob': 3,
 'Scuba Diving': 3,
 'Diving for sponges': 3,
 'Wreck of the schooner Pohoiki ': 3,
 'Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days': 3,
 'Diving ': 3,
 'Standing in knee-deep water': 3,
 'Diving off jetty': 2,
 'Diving for lobsters': 2,
 'Fishing for prawns': 2,
 'Fishing for squid': 2,
 'Fishing for cod': 2,
 'Cruising': 2,
 'Swimming alongside NOAA research vessel Discoverer': 2,
 'Shark diving': 2,
 'Swimming from the New Venture ': 2,
 'Free diving / spearfishing': 2,
 'Splashing ': 2,
 'Boat with 5 men capsized while returning to the Amerique': 2,
 'Swimming / Wading': 2,
 'Swimming ashore from capsized boat': 2,
 'Swimming near jetty': 2,
 'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water': 2,
 'Spearfishing using Scuba': 2,
 'Beach seine netting': 2,
 'Washing his feet': 2,
 'Sitting in shallows': 2,
 'S2N Navy scout plane went down, E.H. Almond & Lieut A.G. Reading in water': 2,
 'Body surfing / treading water': 2,
 'Attempting to kill a shark with explosives': 2,
 'Kitesurfing': 2,
 'Fishing for whiting': 2,
 'Netting shrimp': 2,
 'Thrown overboard': 2,
 'Swimming, ducking for shells in water 0.9 m deep': 2,
 'Diving for beche-de-mer': 2,
 'Free diving / Spearfishing': 2,
 'Kayak fishing': 2,
 'Rowing ': 2,
 'Diving around anchored liner': 2,
 'HMAS Parramatta torpedoed & sunk by the U-559': 2,
 'Boat capsized, swimming ashore': 2,
 'Spearfishing Competition': 2,
 'Fishing for tuna': 2,
 'Scuba diving & spearfishing': 2,
 'Surfing, collided with shark': 2,
 'Free diving, Spearfishing': 2,
 'Bathing in river': 2,
 'Standing ': 2,
 'Kite Boarding': 2,
 'Swimming / escaping imprisonment ': 2,
 'Floating on back': 2,
 'Finning the shark that bit him': 2,
 'The Christie V sank on 11/6/1988, survivors were adrift on a dinghy': 2,
 'Playing in the water': 2,
 'Surfing (lying prone on his board)': 2,
 'Collecting shells': 2,
 'Sitting in the water': 2,
 'Spearfishing / Scuba diving': 2,
 'fishing boat exploded & sank': 2,
 'Jumped overboard ': 2,
 'Diving from canoe': 2,
 'U.S. Airforce C124 enroute from Hickham Air Base to Japan went down. The 3 survivors fashioned raft from mailbags  & were rescued 3 days after the crash.': 2,
 'Air Disaster': 2,
 'Suicide': 2,
 'Standing in waist-deep water': 2,
 'Swimming or surfing': 2,
 'Floating in inner tube': 2,
 'Shooting sharks ': 2,
 'Bathing ': 2,
 '"Flying Tiger" transport plane went down with 5 men onboard': 2,
 'Diving for crayfish': 2,
 'Washing': 2,
 'Hookah diving for sea urchins': 2,
 'Free-diving': 2,
 'Kite boarding': 2,
 'Swimming after his hat': 2,
 'Diving for trochus shell': 2,
 'Standing / Surfing': 2,
 'Diving into water': 2,
 'Dived for a coin': 2,
 'Teasing a shark': 2,
 'Diving?': 2,
 'Aircraft crashed into sea': 2,
 'Shark tagging': 2,
 'Launching rowboat through the surf': 2,
 'Fishing from surf ski': 2,
 'Paddling': 2,
 'Fishing (Seining)': 2,
 'Transatlantic Rowing': 2,
 'Diving for beche-de-mer ': 2,
 'Hoisting shark aboard fishing boat': 2,
 'Kiteboarding': 2,
 'Ocean racing': 2,
 'Swimming / snorkeling': 2,
 'Kayaking ': 2,
 'Spearfishing / Free diving': 2,
 'Jet skiing': 2,
 'Fishing for lobsters': 2,
 'Air disaster': 2,
 'Knocked overboard': 2,
 'Wading (shrimping)': 1,
 'B-24 crashed during a search mission. Survivors in raft for 47 days ': 1,
 'Fell overboard from a frigate & was swallowed by a shark. The captain fired a gun at the shark, and "the creature cast the man out of his throat."': 1,
 "a corsair's boat was overturned": 1,
 'Collecting beche-de-mer': 1,
 'U-177 torpedoed & sank the troopship Nova Scotia': 1,
 "Spearfishing, holding 5' speared fish": 1,
 'Wreck of the USS Somers': 1,
 'Dry shelling': 1,
 'Spearfishing (but on surface)': 1,
 'Swimming or boogie boarding': 1,
 'Fishing from Surfboard': 1,
 'Touching sharks': 1,
 'Boogie boarding, kicked at object in the water': 1,
 'German raider Kormoran was sunk in an engagement with HMAS Sydney': 1,
 'Air Disaster - Piper aircraft crashed into the sea, killing all on board': 1,
 'Watching the shark feeding on a dead pinniped': 1,
 'Fell overboard from the Malacca': 1,
 'Swimming ashore from swamped 13-ft boat': 1,
 'Scuba diving & filming': 1,
 'Free diving for sinkers': 1,
 'Working on the bridge when he fell into the river': 1,
 'Testing movie camera in full diving dress': 1,
 'Dog paddling or standing': 1,
 'Wakeboarding': 1,
 'Stuffing a shark into an automobile': 1,
 'Treading water/ Surfing': 1,
 'Photographing the shark': 1,
 'Diving for trochus from lugger': 1,
 'Dived overboard to retrieve dinghy': 1,
 'Standing on his hands': 1,
 'Floating on an inflatable raft': 1,
 'Filming underwater, carrying powerhead': 1,
 'Spear fishing, removing fish from spear': 1,
 'Free diving with seals': 1,
 'Survived US Naval aircraft crash, climbing onboard rescue vessel when he fell back into sea ': 1,
 'Swimming around anchored ship': 1,
 'Ferry boat sank': 1,
 "Onboard 21' powerboat that capsized in rough seas": 1,
 'Swimming with goggles': 1,
 'Photographing fish': 1,
 'Dragging stranded shark into deeper water': 1,
 'Body surfing?': 1,
 "Captured Allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks": 1,
 'Fell from the jetty': 1,
 'Swimming to canoe': 1,
 'Plane crashed in water, men in life raft': 1,
 'Diving (shell maintenance)': 1,
 'SS Ethel Skakel foundered in Central America Hurricane of 1941': 1,
 'Wooden fishing boat': 1,
 'Swimming to shore from capsized sailboat': 1,
 'Walking, carrying surfboard & stepped on shark': 1,
 'Free diving & spearfishing (ascending)': 1,
 'Collecting fish by lamplight in gully': 1,
 'Playing with a frisbee in the shallows': 1,
 'Swimming off yacht': 1,
 'Sinking of the ferryboat Bongbong 1': 1,
 'Free diving with goggles': 1,
 'Diving (Hookah)': 1,
 'Ran into the water': 1,
 'Light aircraft ditched at sea': 1,
 'Fishing from shore, washed into the sea': 1,
 'Survived crash of two-engine  C-46 transport plane carrying 62 migrant workers from Puerto Rico to USA ': 1,
 'Restraining a beached shark': 1,
 'Surfing, but standing in water alongside board': 1,
 'Washed overboard from the barque Mary Eady': 1,
 'Fishing from surfski': 1,
 'Fishing, speared shark upset canoe & man fell in water': 1,
 'Bitten after dhow shipwrecked': 1,
 'Motor boat Rebel Belle lost': 1,
 'Trailing hand in the water': 1,
 'Swimming along a row of nets': 1,
 'Sea disaster, foundering of the cargo vessle M/V Dorolonda': 1,
 'Sea Disaster, sinking of the fishing  launch Mavis': 1,
 'On fishing boat & trailing hand in the water': 1,
 '"Swimming vigorously"': 1,
 'The cutter yacht Cutty Sark sank': 1,
 'Spearfishing, speared fish retreated to cave where shark grabbed his arm': 1,
 'Spearfishing, carrying fish on belt': 1,
 'Diving / UW photography': 1,
 'Retrieving meat from a cage in the water': 1,
 'Kayaking or Wave skiing': 1,
 'Free diving / modeling': 1,
 'Diving alongsidethe steamship Ranelagh ': 1,
 'Treading water after survivng crash of the US Navy airship K-74 that was hit by the German submarine U-134': 1,
 'Scuba diving ': 1,
 'Diving for Abalone': 1,
 'Fishing for shrimp': 1,
 'Steinhart Aquarium': 1,
 '17 Maldivians adrift in open boat for 31 days': 1,
 'Lying prone on surfboard': 1,
 'Diving for sinkers': 1,
 'Fishing, removing the shark from his line': 1,
 'Scuba diving for lobsters': 1,
 "Diving in Sharkey's Reef restaurant�s aquarium": 1,
 'Sunbathing on beach when he saw child being attacked by the shark': 1,
 'Thrown from destroyer when shell hit': 1,
 'Washing a dog': 1,
 'Free diving for molluscs': 1,
 'Free diving for shell': 1,
 'Knocked into the water': 1,
 'Wading & pushing dinghy toward  the shallows': 1,
 'Collecting marine specimens': 1,
 'Attempting to catch a crocodile': 1,
 'Sittting in water with his child': 1,
 'Spearfishing/ filming': 1,
 'Spearfishing, speared a small shark': 1,
 'Fishing for tarpon': 1,
 'Dynamiting fish': 1,
 'Fishing & spearfishing': 1,
 'Shipwrecked pearling schooner': 1,
 'The schooner Tahitienne foundered in a hurricane': 1,
 'Jumped overboard from Norwegian steamship Venator': 1,
 'Fishing, hauling in net, shark in net': 1,
 'Fishing, when line became snagged on rock & he dived into water to free it ': 1,
 'Boarding a ship': 1,
 'Treading for clams': 1,
 'Hookah Diving': 1,
 'Standing on ship deck': 1,
 'Finning the shark': 1,
 'Swimming / Body surfing': 1,
 'The Cuban freighter Libertad was torpedoed and sunk by the German submarine U-129': 1,
 'British ship, Britannia,  was loading lumber. He was bathing': 1,
 'Water-skiing': 1,
 'Closed circuit diving (submerged). Diving to recover jettisoned packets of opium for police': 1,
 'Bathing close inshore': 1,
 'Crabbing (spearing crabs)': 1,
 'Swept out to sea by the tsunami, she clung  to a log for 24 hours': 1,
 'Commercial diver (submerged or treading water)': 1,
 'Pearl diving, but standing in the water': 1,
 'Fell overboard from the Sobella': 1,
 'Gathering fish stunned by dynamite': 1,
 'Fishing / cleaning fish, dived into water to retrieve a lost fish': 1,
 'Body boarding ': 1,
 'Probabable drowning': 1,
 'Swimming / Body Surfing': 1,
 'Fishing from prawn trawler': 1,
 'Testing classified underwater electronic gear for Raytheon Corporation, vessel torn apart by explosion': 1,
 'Surfing, but treading water': 1,
 'Fishing, holding fish in right hand': 1,
 'Collecting ornamental fish': 1,
 'Fishing from dinghy': 1,
 'canoeing': 1,
 'Tuna fishing, standing on stern platform that was submerged by waves': 1,
 'Vessel capsized, wading ashore carrying an oar': 1,
 'Swimming / jumping off a jetty': 1,
 'Fell from cliff while fishing & disappeared in strong current': 1,
 'A dhow capsized': 1,
 'Paddle-boarding': 1,
 'Spearfishing, had fish on his spear': 1,
 'Removing shark from net': 1,
 'Boat, with 42 passengers onboard, capsized in rough seas': 1,
 'Paddle Skiing': 1,
 'Fishing, fell from rocks & disappeared': 1,
 'Conducting research': 1,
 'Diving, retrieving film package from Titan 3C rocket': 1,
 'Diving for beche-de-mer from lugger': 1,
 'Swimming after being swept into sea by a large wave': 1,
 'Fishing in knee-deep water': 1,
 'Boat exploded': 1,
 'Trailing the field in a surf race': 1,
 'Swimming /  boogie boarding': 1,
 'Diving from the lugger San, operated by the Protector of the Aborigines': 1,
 'Diving (Helmet) for sponges': 1,
 'The USS Wahoo torpedoes & sank the Japanese troop transport Buyo Maru': 1,
 'Swimming in hip-deep water': 1,
 'Dragging a shark': 1,
 'Small vessel with 13 men on board capsized crossing the bar and 6 men drowned.  The 7 survivors were swimming to shore': 1,
 'Rowing toward snapper grounds': 1,
 'Schooner sank during a storm': 1,
 'Floating on raft': 1,
 'Swimming alongside the SS Kearsarge': 1,
 'Vehicle plunged over cliff into the water': 1,
 'Sea Disaster, sinking of the motorship Wingate': 1,
 'Fishing, casting in the surf': 1,
 'yachtsman in a zodiac': 1,
 'Accidentally thrown overboard & treading water while awaiting rescue': 1,
 'Air/Sea Disaster involving C-54 Air Force Transport No. 2686 with 37 on board': 1,
 'Attempting to drive shark from area': 1,
 'Clinging to overturned rowing boat': 1,
 'Fishing, standing in waist-deep water': 1,
 'Bathing / standing': 1,
 'Competing in spearfishing championship & towing dead fish': 1,
 'Collecting fish ': 1,
 'Swimming with pod of dolphins': 1,
 'Sinking of the dredge World Atlas': 1,
 'Swimming/': 1,
 'Landing hooked shark in boat': 1,
 "Holding shark's tail ": 1,
 'Playing in the surf with his 2 dogs': 1,
 'Bathing with her mother': 1,
 'Holding shark on leader & dangling it above the water': 1,
 'Sleeping in anchored boat': 1,
 'Pacific Seafarer of US Navy': 1,
 'Swept off deck of S.S.Frontenac enroute from West Indies to US': 1,
 'Fishing, Struck by another shark when removing shark from line': 1,
 "Fishing, removing gaff from shark's mouth": 1,
 'Jumped overboard to rescue a man': 1,
 'Wreck of the Sovereign': 1,
 'Dragging banana seeds through the shallows': 1,
 'Removing fish from a trap': 1,
 'boat with 46 people on board capsized': 1,
 'Spearfishing using scuba': 1,
 'Bodyboarding': 1,
 'Freediving, inspecting Kaunakakai wharf construction after blasting & dredging ': 1,
 'Walking in shallows': 1,
 'Free diving but treading water at surface': 1,
 'Hauling in net with shark in it': 1,
 'Fishing for trout ': 1,
 'Hookah diving for abalone (submerged)': 1,
 'Playing ': 1,
 'Greek steamship Lakonia caught fire, 98 of her 646 passengers, and 30 of her crew of 376 perished': 1,
 'Murdered': 1,
 'Washing his pig in preparation for a religious ceremony': 1,
 'Adrift on a raft ': 1,
 'Fishing, thrown into water by heavy sea, clinging to rocks at the water line': 1,
 'Scuba diving, reportedly also spearfishing': 1,
 'Scuba Diving for scallops': 1,
 'Playing in knee-deep water': 1,
 'Fishing for perch': 1,
 'Fell off aircraft carrier': 1,
 'Diving off wharf': 1,
 'Crew swimming alongside their anchored ship': 1,
 'Surf paddling': 1,
 'Sitting': 1,
 'H.M.S. Cornwall & H.M.S.Dorsetshire sunk by Japanese dive bombers. Officers & men in the water formed a circle with 60 of their dead in the center for 36 hours': 1,
 'Free diving for abalone (ascending)': 1,
 'Overturned skiff': 1,
 'Swimming in canal': 1,
 "Days before the surrender of Singapore, the 3 men escaped to Sumatra where they acquired a 17' dinghy. After 125 days at sea they drifted back to Sumatra": 1,
 'Washing horses': 1,
 'Sitting on side of dinghy mending a net': 1,
 'Floating on inner tube after diving for lobster': 1,
 'Lying in 2 feet of water': 1,
 'Harpooning turtles': 1,
 'Ship lay at anchor & man was working on its rudder': 1,
 'The MV Dona Marilyn sank in Typhoon Unsang with the loss of 389 lives': 1,
 'Sinking of the M/V Mindoro during a typhoon': 1,
 'Spearfishing / freediving': 1,
 'Treading water, waiting for a wave': 1,
 'Rowing an inflatable dinghy': 1,
 'Wrangling a shark': 1,
 'Attempting to drag hooked shark ashore by its tail': 1,
 'Lying on surfboard': 1,
 'Swimming from shore to anchored sailboat': 1,
 'Tzenny Chandris, a Greek freighter laden with scrap iron, foundered in heavy weather': 1,
 'Sea Disaster : Wreck of the Carrie E. Long': 1,
 'Hunting seals': 1,
 'Scuba diving for bivalves': 1,
 'Spearfishing or fishing': 1,
 'Sea Disaster, sinking of the  SS Vestris': 1,
 'Swimming with mask & snorkel': 1,
 'Swimming to avoid capture': 1,
 'Fishing, holding fish': 1,
 'Swimming outside fishing net': 1,
 'A 210-ton brig was sunk by a Japanese submarine. Some of the survivors were machine-gunned & some were taken by sharks': 1,
 'Columbian petrol barge Rio Atrato burned and sank': 1,
 "Competing in U/W endurance record, standing beside drum in 10' of water": 1,
 'Body surfing ': 1,
 'Dived onto shark from floating stage': 1,
 'Free diving for sponges': 1,
 'Free diving for crayfish': 1,
 'boat from ship Josephine capsized in squall': 1,
 'Surfing & filming dolphins': 1,
 "Sinking of the 40' Esperanza off St. Maartin with 36 refugees on board": 1,
 'Fell or jumped overboard from the liner Rhynland': 1,
 'Swimming between  anchored  pearling luggers': 1,
 'Crossing inlet in a boat, seen fighting sharks with his oar, sharks smashed boat': 1,
 'Swimming, when caught in heavy seas': 1,
 'Swimming underneath house on pilings': 1,
 'Dutch merchant ship Zaandam torpedoed  by the U-174 amidships, sank & dozens of survivors took to rafts & boats. One man, Izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down': 1,
 'Ship Mariston torpedoed & sunk': 1,
 'Playing on rock, slipped & fell into the water': 1,
 'Standing / Bathing': 1,
 'Fishing for white shark': 1,
 'Swimming crawl stroke': 1,
 'Spearfishing with Joe Turner (24). Shark attracted to speared halibut on belt of one diver, tried to bite Ide�s speargun & he shot it in the mouth': 1,
 'Bringing hooked, harpooned shark onboard boat': 1,
 'Spearfishing with Scuba gear': 1,
 'Hurricane & Tidal Wave': 1,
 "Lying on the bottom of a 16' dinghy": 1,
 "Overcome by CO fumes, fell overboard from 36' fishing cruiser & prop slashed arm": 1,
 'Wading?': 1,
 "63' fishing boat Sno' Bay foundered": 1,
 'Sea Disaster, wreck of the  SS Norwich City': 1,
 'Scuba diving, hand feeding sharks': 1,
 'The steamships Thingvalla and Geiser collided': 1,
 'Spearfishing, holding mesh bag with speared fish': 1,
 'Standing in inner tube': 1,
 'Washing sand off a speared fish': 1,
 'Oyster fishing': 1,
 'Diving in tuna net': 1,
 'Pulling hooked salmon to boat': 1,
 'Attaching a line at sea': 1,
 'His ship, the US destroyer Duncan DD 485, had been  sunk by crossfire from Japanese warships. He was wearing a kapok lifejacket & using 2 aluminum powder tins for floatation  ': 1,
 'Standing in chest-deep water': 1,
 'Hunting lobsters in 2.4 m of water': 1,
 'Spearfishing / scuba diving': 1,
 'Wreck of the schooner Driver': 1,
 'Fishing in ankle-deep water': 1,
 'Riding horseback across the creek': 1,
 'On inflatable raft': 1,
 'Swimming, towing the shark': 1,
 'Parachuted from balloon': 1,
 'Free diving (but on surface)': 1,
 'After rowing skiff was holed by shark, he was attempting to swim ashore': 1,
 'Swimming / treading water': 1,

In [ ]:
di = df['']